"""baseline schema

Revision ID: ee1e5e083432
Revises: 
Create Date: 2026-08-12 22:38:19.563216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1e5e083432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('restaurants', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('restaurants', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('restaurants', 'food_style',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('restaurants', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('restaurants', 'price_range',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurants', 'vibe',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'vibe',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('restaurants', 'price_range',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurants', 'rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('restaurants', 'food_style',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('restaurants', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('restaurants', 'location',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('restaurants', 'name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
